[build]
  base = "frontend"
  command = "npm install && ng build --configuration production"
  publish = "dist/frontend"

[build.environment]
  API_URL = "https://control-debts.onrender.com"
  PUBLISH_DIR = "dist/frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
