# Usa Eclipse Temurin con JDK 17 (basado en Alpine)
FROM eclipse-temurin:17-jdk-alpine AS build

# Copia el código fuente y el wrapper de Maven
WORKDIR /app
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

COPY src ./src
RUN ./mvnw clean package -DskipTests

# Segunda etapa: imagen ligera para ejecutar
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]