# Usa una imagen base con JDK 17
FROM openjdk:17-jdk-slim AS build

# Copia el código fuente y el wrapper de Maven
WORKDIR /app
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

COPY src ./src
RUN ./mvnw clean package -DskipTests

# Segunda etapa: imagen ligera para ejecutar
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]