spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USER:postgres.pyrimtmytbvjukkukrqb}
spring.datasource.password=${DB_PASSWORD:fdmype.456cbba}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b2a60bb1fa25d3dfb8cd4e207dbea8253a}
jwt.expiration=86400000
